### ISSUE TITLE
Parser UI

### ISSUE THREAD

**Issue by xiedidan** [Orientsoft/conalog-front#14]
Ref to: [Coanlog Issue #54](https://github.com/Orientsoft/conalog/issues/54)

What we need:
1. Parser list - CRUD
2. Parser status list - start / stop / last activity / etc...
3. Parser **instance** list in parser status list

**Comment by xiedidan** [comment]
- [ ] 页面设计，操作流程设计 3天 3.22 （每天Check，提交Mock图，操作流程说明文档）
- [ ] 页面实现 5天 3.28 （Checkpoint：Parser - 3.24，Status - 3.28，提交React页面）
- [ ] 逻辑实现 5天 4.4 （Checkpoint：Parser - 3.30， Status - 4.4，提交逻辑代码）
- [ ] 测试与文档 5天 4.11（Checkpoint：4.6，提交整体代码）

**Comment by JiangJun1994** [comment]
##操作流程文档说明
parser：
主要实现对parser的增删改查：
1.	增：点击add图标即弹出文本框，填写信息点击确认即增加一条parser。
2.	删：table的operation列点击delete，弹出确认框，确定删除点击确定，取消删除点击取消。
3.	改：table的operation列点击edit，弹出文本框，进行编辑，完成编辑点击确定，取消编辑点击取消。
4.	查：在search框中填入parser名，对应的信息行即显示在table中

parser status：
主要增加实例进程：

点击table首列的加号图标，即可展开instance list；
点击table中instance列的add button 即可展开instance list并且新增一个instance；
instance list每行有stop按钮，点击stop按钮，instance进程即消失。

**Comment by JiangJun1994** [comment]
操作流程文档说明
=====
## Parser
主要实现对parser的增删改查：
1.	增：点击add图标即弹出文本框，填写信息点击确认即增加一条parser。
2.	删：table的operation列点击delete，弹出确认框，确定删除点击确定，取消删除点击取消。
3.	改：table的operation列点击edit，弹出文本框，进行编辑，完成编辑点击确定，取消编辑点击取消。
4.	查：在search框中填入parser名，对应的信息行即显示在table中
## Parser status
主要增加实例进程：
1.	点击table首列的加号图标，即可展开instance list。
2.	点击table中instance列的start button 即可展开instance list并且新增一个instance。
3.	instance list每行有stop button，点击stop button，instance进程即消失。

**Comment by JiangJun1994** [comment]
![conalog-parser](https://cloud.githubusercontent.com/assets/25809468/24129412/7dcb1628-0e1d-11e7-9d22-2fd415ee1bf3.png)
![parser status](https://cloud.githubusercontent.com/assets/25809468/24129598/b7100b36-0e1e-11e7-9d38-62123720d22b.png)

**Comment by xiedidan** [comment]
Just merged to master, well done.
