### ISSUE TITLE
Cert密码查看

### ISSUE THREAD

**Issue by xiedidan** [Orientsoft/conalog-front#3]
目前Cert列表使用了折叠行来隐藏密码
是否有更安全的方式

**Comment by xiedidan** [comment]
@hyq2015 修改的时候开个新Fork，Commit之后，合并分支之前请先通知我Review一下
commit的时候-m参数提到Issue #3就可以在Issue里显示相关提交

**Comment by xiedidan** [comment]
任务计划：

- [ ] 了解技术栈（Reflux、ES6） 2天

- [ ] 熟悉Conalog-Front代码架构和Git开发模式 2天

- [ ] Issue思路和实现 5天

- [ ] 测试和文档 2天

**Comment by xiedidan** [comment]
参考：
[ES6新特性概览 - 了解技术栈的时候看这个即可](http://www.cnblogs.com/Wayou/p/es6_new_features.html)
[ECMAScript 6 入门 - 阮一峰的书，具体做的时候参考](http://es6.ruanyifeng.com/)
[Bluebird Why Promise - Bluebird文档，了解Promise的来由和基本用法](http://bluebirdjs.com/docs/why-promises.html)
[Git分支管理策略 - 了解Git开发模式](http://www.ruanyifeng.com/blog/2012/07/git.html)

**Comment by JiangJun1994** [comment]
Issue3 解决思路：
在table中新增一列为password，并且将密码设置为******后面加个图标，点击图标显示密码，再点击图标恢复******。 
具体步骤：
为图标添加点击事件，
在AppStore state里添加showPass属性，并赋值为false，当showPass值为false时，密码为******，当showPass值为true时，密码为原本的值。每点击一次图标，showPass的值会在true和false之间切换，以此来影响密码的显示。
完成时间：预计三天

**Comment by xiedidan** [comment]
1. 点击显示密码之后是全部密码都会显示吗（添加一个showPass属性就会造成全局显示）
2. 建议鼠标放在显示密码图标上的时候，对应的那个密码明文，其余密码不变

**Comment by JiangJun1994** [comment]
不是显示全部，就是点击图标，对应的密码会显示。

**Comment by xiedidan** [comment]
OK，showPass具体添加到哪里？

**Comment by JiangJun1994** [comment]
我重新理了下思路：
在AppAction里面添加 showPass,
在AppStore的state里面添加 originPass:"******"（密码的初始值）
 onShowPass:function(pass){
    if(state.originPass=="******"){
        state.originPass=pass
        this.trigger(state)
    }else {
        state.originPass=="******"
        this.trigger(state)
    }
  }
在Cert里面添加：onShowPass(e){
        AppActions.showPass(e.target.dataset.pass)
    }
在table里面添加一列：
  {
        title:'Password',
        dataIndex:'pass',
        render:(record)=>{
          <p><span>{this.props.appStore.originPass}</span><Icon data-pass={record.pass} style="eye" onClick={this.onShowPass.bind(this)}></Icon></p>
        }
      },

**Comment by JiangJun1994** [comment]
在table里面添加一列：
  {
        title:'Password',
        dataIndex:'pass',
        render:(record)=>{
          <p><span>{this.props.appStore.originPass}</span><Icon data-pass={record.pass} style="eye" onClick={this.onShowPass.bind(this)}></Icon></p>
        }
      },

**Comment by JiangJun1994** [comment]
上面没有显示完全，密码为：{this.props.appStore.originPass}，然后图标添加onShowPass事件

**Comment by xiedidan** [comment]
OK. Well done.
